<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>java异常的学习 | YuKai&#39;s blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="最近的写代码的过程中，遇到很多异常的处理，以前上大学的时候写代码，遇到异常直接给个try catch了事，只是停留在看懂异常能够找出异常抛出点的水平。真正写代码的时候，不了解java的异常机制给自己编程带来很多不便，基础知识很重要！学习之～～

异常分类
java异常中的异常大体上可分为两类：Error 与 Exception，他们都继承自Throwable">
<meta property="og:type" content="article">
<meta property="og:title" content="java异常的学习">
<meta property="og:url" content="http://yukai.space/2016/12/13/java异常的学习/index.html">
<meta property="og:site_name" content="YuKai's blog">
<meta property="og:description" content="最近的写代码的过程中，遇到很多异常的处理，以前上大学的时候写代码，遇到异常直接给个try catch了事，只是停留在看懂异常能够找出异常抛出点的水平。真正写代码的时候，不了解java的异常机制给自己编程带来很多不便，基础知识很重要！学习之～～

异常分类
java异常中的异常大体上可分为两类：Error 与 Exception，他们都继承自Throwable">
<meta property="og:image" content="http://yukai.space/2016/12/13/java异常的学习/java.png">
<meta property="og:updated_time" content="2017-11-02T01:44:09.720Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="java异常的学习">
<meta name="twitter:description" content="最近的写代码的过程中，遇到很多异常的处理，以前上大学的时候写代码，遇到异常直接给个try catch了事，只是停留在看懂异常能够找出异常抛出点的水平。真正写代码的时候，不了解java的异常机制给自己编程带来很多不便，基础知识很重要！学习之～～

异常分类
java异常中的异常大体上可分为两类：Error 与 Exception，他们都继承自Throwable">
<meta name="twitter:image" content="http://yukai.space/2016/12/13/java异常的学习/java.png">
  
  
    <link rel="icon" href="/favicon.png">
  
  
    
  
  <link rel="stylesheet" href="/css/style.css">
  

</head>

<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    
    <div id="header-inner" class="inner">
      <nav id="sub-nav">
        
        <a id="nav-search-btn" class="nav-icon" title="搜索"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" results="0" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="http://yukai.space"></form>
      </div>
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/">首页</a>
        
          <a class="main-nav-link" href="/archives">归档</a>
        
          <a class="main-nav-link" href="/tools">工具</a>
        
          <a class="main-nav-link" href="/page">关于</a>
        
      </nav>
      
    </div>
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">YuKai&#39;s blog</a>
      </h1>
      
        <h2 id="subtitle-wrap">
          <a href="/" id="subtitle">好好学习，天天向上</a>
        </h2>
      
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-java异常的学习" class="article article-type-post" itemscope itemprop="blogPost">
  <div class="article-meta">
    <a href="/2016/12/13/java异常的学习/" class="article-date">
  <time datetime="2016-12-13T13:46:52.000Z" itemprop="datePublished">2016-12-13</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      java异常的学习
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <!-- Table of Contents -->
        
        <blockquote>
<p>最近的写代码的过程中，遇到很多异常的处理，以前上大学的时候写代码，遇到异常直接给个try catch了事，只是停留在看懂异常能够找出异常抛出点的水平。真正写代码的时候，不了解java的异常机制给自己编程带来很多不便，基础知识很重要！学习之～～</p>
</blockquote>
<h2 id="异常分类"><a href="#异常分类" class="headerlink" title="异常分类"></a>异常分类</h2><img src="/2016/12/13/java异常的学习/java.png" alt="java异常体系" title="java异常体系">
<p>java异常中的异常大体上可分为两类：Error 与 Exception，他们都继承自Throwable</p>
<a id="more"></a>
<h3 id="Error："><a href="#Error：" class="headerlink" title="Error："></a>Error：</h3><p>Error表示一些无法恢复的错误，会导致应用程序中断。比如我们喜闻乐见的OutOfMemoryError(内存溢出)， StackOverflowError(堆栈溢出)等，就是一种Error类型的异常。面对这种类型的异常在我们的应用程序中一般是无法挽救的，将直接导致程序错误退出。因此我们在代码中一般不必去特别关心这种类型的异常。</p>
<p><a href="https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html" target="_blank" rel="external">Error类型的异常及其子类</a></p>
<h3 id="Exception"><a href="#Exception" class="headerlink" title="Exception:"></a>Exception:</h3><p>Exception是一般常见的异常，我们的应用程序可以处理这些异常，比如NullPointerException、IndexOutOfBoundsException等等。发生这些异常时，可以选择通过捕获这些异常进行处理，使程序可以继续往下执行。</p>
<p>Exception又可以分为CheckException(检测型异常)与UncheckException(非检测型异常)。</p>
<p>在Exception的子类当中，非检测型异常为RuntimeException及其子类，剩下的异常则为检测型异常。</p>
<h4 id="检测型异常"><a href="#检测型异常" class="headerlink" title="检测型异常"></a>检测型异常</h4><p>所谓检测型异常，表示其接受编译器的检测，比如</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div></pre></td><td class="code"><pre><div class="line">public void readFile(String filePath)&#123;</div><div class="line">        //编译无法通过</div><div class="line">		File file = new File(filePath);</div><div class="line">		FileReader fileReader = new FileReader(file);//FileNotFoundException</div><div class="line">		BufferedReader bReader = new BufferedReader(fileReader);</div><div class="line">		String line = null;</div><div class="line">		while ((line = bReader.readLine()) != null) &#123;//IOException</div><div class="line">			System.out.println(line);</div><div class="line">		&#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>编译上述代码，编译器会报错，编译无法通过。<br>如果是用Eclipse等ide去写这段代码，ide通常就会告诉你这段代码有错误。原因是上述代码会抛出检测型异常IOException。有以下两种修复错误的方法：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div></pre></td><td class="code"><pre><div class="line">//第一种</div><div class="line">public void readFile(String filePath) throws IOException&#123;</div><div class="line">		File file = new File(filePath);</div><div class="line">		FileReader fileReader = new FileReader(file);</div><div class="line">		BufferedReader bReader = new BufferedReader(fileReader);</div><div class="line">		String line = null;</div><div class="line">		while ((line = bReader.readLine()) != null) &#123;</div><div class="line">			System.out.println(line);</div><div class="line">		&#125;</div><div class="line">&#125;</div><div class="line">//第二种</div><div class="line">public void readFile(String filePath) &#123;</div><div class="line">		File file = new File(filePath);</div><div class="line">		try &#123;</div><div class="line">			FileReader fileReader = new FileReader(file);</div><div class="line">			BufferedReader bReader = new BufferedReader(fileReader);</div><div class="line">			String line = null;</div><div class="line">			while ((line = bReader.readLine()) != null) &#123;</div><div class="line">				System.out.println(line);</div><div class="line">			&#125;</div><div class="line">		&#125; catch (IOException e) &#123;</div><div class="line">			// TODO: handle exception</div><div class="line">		&#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>第一种方式通过声明throws关键字将该异常继续向上抛出，这种方式下，该方法就抛出了检测型异常，他的调用者就会遇到一样的问题，调用者可以选择使用这种方式继续向调用链上层抛出，或者采用第二种方式处理异常。</p>
<p>第二种方式通过将抛出异常的代码使用try..catch块包裹起来，处理该异常。这种方式下他的调用者无需再次处理该异常。</p>
<p>上面这种类型的异常就是检测型异常，我们必须显示的去处理他，代表的有SQLException、IOException等等。</p>
<h4 id="非检测型异常"><a href="#非检测型异常" class="headerlink" title="非检测型异常"></a>非检测型异常</h4><p>与检测型异常相对的，编译阶段不会检测这种类型的异常，当代码中有这种类型的异常抛出时，我们不需要像上面那样显示的处理他，比如：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">public void test() &#123;</div><div class="line">        //编译可以通过</div><div class="line">		throw new NullPointerException();</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>通过throw关键字抛出了一个NullPointerException异常，该异常是RunTimeException的子类，是一个非检测类型的异常。这种类型的异常一般是由程序逻辑错误引起的，比如空指针或者数组越界等等。</p>
<p>对于非检测类型的异常，我们也可以去使用try..catch捕获他，从而进行一些处理。如果我们没有捕获处理这个异常，系统会把异常一直往上层抛，一直到最上层，如果是多线程就由Thread.run()抛出，如果是单线程就被main()抛出。抛出之后，如果是线程，<strong>这个线程也就退出了</strong>。如果是主程序抛出的异常，<strong>那么这整个程序也就退出了</strong>。</p>
<p>Error实际上也是一种非检测型异常。</p>
<h2 id="异常处理"><a href="#异常处理" class="headerlink" title="异常处理"></a>异常处理</h2><h3 id="关键字"><a href="#关键字" class="headerlink" title="关键字"></a>关键字</h3><p>了解了异常的分类，我们就可以愉快的处理异常了。记得上大学的时候写的代码，由于不理解java的异常机制，每当遇到检测型异常时，ide会要求在代码中处理这种情况。于是简单的try..catch解决，并在catch块中 e.printStackTrace()，就解决了IDE的报警问题。现在想来，这种代码如果运行在生产环境中，将会多么可怕。</p>
<p>通过上面的总结，我们已经了解了四个关键字：try catch throw throws.</p>
<p>throw表示将要抛出一个异常，后面跟一个Throwable的实例，throws置于函数的声明当中，表示该函数将会抛出何种类型的异常。</p>
<p>try catch 一般配合使用，还有一个关键字finally,也是与try catch 配合使用的。有这三种使用方式：</p>
<p>try..catch  try..finally try..catch..finally</p>
<p>catch 可以有多个，try只能有一个，finally可选。</p>
<p>finally用于保证一些资源的释放，因为一般情况下，finally中的语句总会在方法返回之前得到执行。</p>
<h3 id="try-catch-finally执行顺序"><a href="#try-catch-finally执行顺序" class="headerlink" title="try catch finally执行顺序"></a>try catch finally执行顺序</h3><p>try catch finally的执行顺序为 try-&gt;catch-&gt;finally。</p>
<p>有多个catch时，按照catch块的先后顺序进行匹配，一旦一个异常与一个catch块匹配，则不会再与后面的catch块进行匹配。<br>因此，如果我们使用多个catch块捕获异常时，如果多个catch块捕获的异常具有继承关系，注意把继承链中低层次(也就是子类)的放在前面，把继承链中高层次的(也就是父类)放在后面。<br>这样做的目的很简单，就是尽量使异常被适合的catch所捕获，这样处理起来比较明确。</p>
<p>finally块中的代码一般是在try与catch内的控制转移语句执行之前执行的，用来做一些资源释放的操作。控制转移语句包括：return、throw、break 和 continue。</p>
<p>关于finally块的详细解析，参考<a href="https://www.ibm.com/developerworks/cn/java/j-lo-finally/" target="_blank" rel="external">关于 Java 中 finally 语句块的深度辨析</a></p>
<p>另外有一点需要注意：不要在finally中return，因为finally中的return会覆盖已有的返回值，比如try或者catch中的返回值。比如：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div></pre></td><td class="code"><pre><div class="line">public class TestException &#123;</div><div class="line">    public static void main(String[] args) &#123;</div><div class="line">        String str = new TestException().readFile();</div><div class="line">        System.out.println(str);</div><div class="line">    &#125;</div><div class="line"> </div><div class="line">    public String readFile() &#123;</div><div class="line">        try &#123;</div><div class="line">            FileInputStream inputStream = new FileInputStream(&quot;D:/test.txt&quot;);</div><div class="line">            int ch = inputStream.read();</div><div class="line">            return &quot;try&quot;;</div><div class="line">        &#125; catch (FileNotFoundException e) &#123;</div><div class="line">            System.out.println(&quot;file not found&quot;);</div><div class="line">            return &quot;FileNotFoundException&quot;;</div><div class="line">        &#125;catch (IOException e) &#123;</div><div class="line">            System.out.println(&quot;io exception&quot;);</div><div class="line">            return &quot;IOException&quot;;</div><div class="line">        &#125;finally&#123;</div><div class="line">            System.out.println(&quot;finally block&quot;);</div><div class="line">            //return &quot;finally&quot;;</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>D:/test.txt 并不存在，执行结果为:file not found    finally block   FileNotFoundException<br>去掉finally中的注释，执行结果为：file not found    finally block   finally</p>
<h2 id="一些建议"><a href="#一些建议" class="headerlink" title="一些建议"></a>一些建议</h2><p>了解了异常机制的基本原理，不一定能够很好的处理异常。当我们遇到异常需要处理的时候，需要遵循几个原则，才能写出更好的代码：</p>
<h3 id="不要使用空的catch块"><a href="#不要使用空的catch块" class="headerlink" title="不要使用空的catch块"></a>不要使用空的catch块</h3><p>正如前面所说，上学的时候遇到异常时，直接try..catch了事，只是简单地e.printStackTrace(),把堆栈打印出来了。这样可能对定位异常比较有帮助，但是对异常的处理却没有帮助，既没有处理异常，上层代码也无法得知异常的抛出，<br>程序会继续运行，有可能出现无法预料的结果。当然，如果程序的逻辑容忍异常可以不用处理，那么可以不处理异常，简单的输出到日志记录即可。处理还需视实际情况而定。</p>
<h3 id="在能够处理异常的地方处理异常"><a href="#在能够处理异常的地方处理异常" class="headerlink" title="在能够处理异常的地方处理异常"></a>在能够处理异常的地方处理异常</h3><p>换句话说，就是在高层代码中处理异常。尽量将异常抛给上层调用者，由上层调用者统一进行处理。这样会使得程序流程比较清晰。</p>
<h3 id="日志打印"><a href="#日志打印" class="headerlink" title="日志打印"></a>日志打印</h3><p>只在必要的地方打印日志，如只在异常发生的地方输出日志，然后将异常抛到上层。这样比较容易定位异常，避免每次向上抛出异常时都打印日志，反复打印同一个异常会使得日志变得混乱</p>
<h3 id="检测异常与非检测异常的选择"><a href="#检测异常与非检测异常的选择" class="headerlink" title="检测异常与非检测异常的选择"></a>检测异常与非检测异常的选择</h3><p>为可恢复的条件使用检查型异常，为编程错误使用运行时异常</p>
<p>在web项目中，我们经常把代码层次分为controller，service,dao等几层。在dao层中一搬会抛出SQLException,这就使得他的调用者必须显示的捕获该异常或者继续抛出。这样提高了代码的耦合性，污染了上层代码。<br>在比如接口的声明当中，我们为方法声明了一个检测型异常，那么他的所有实现类都必须作出同样的声明，即使实现类不会抛出异常。而且，所有的调用者都必须显示的捕获异常或者抛出异常，异常就会扩散开来，会使代码变得混乱。<br>所以我们应该正确的选择检测型异常和非检测型异常。个人认为，检测型异常的意义就在于提醒用户进行处理，比如一些资源的释放等等。如果该异常出现的很普遍，需要提醒调用者进行处理，那么就是用检测型异常，否则，就使用非检测型异常。</p>
<p>对于已经抛出的检测型异常，我们可以进行封装处理，比如对于第一种情况，污染上层代码的问题：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div></pre></td><td class="code"><pre><div class="line">//处理前</div><div class="line">public Data getDataById(Long id) throw SQLException &#123;</div><div class="line"> //根据 ID 查询数据库</div><div class="line">&#125;</div><div class="line"></div><div class="line">//处理后</div><div class="line">public Data getDataById(Long id) &#123;</div><div class="line">     try&#123;</div><div class="line">            //根据 ID 查询数据库</div><div class="line">     &#125;catch(SQLException e)&#123;</div><div class="line">            //利用非检测异常封装检测异常，降低层次耦合</div><div class="line">            throw new RuntimeException(SQLErrorCode, e);</div><div class="line">     &#125;finally&#123;</div><div class="line">            //关闭连接，清理资源</div><div class="line">     &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>我们将一个检测型异常封装成了非检测型异常向上抛出。</p>
<h3 id="不要使用Exception捕捉所有潜在的异常"><a href="#不要使用Exception捕捉所有潜在的异常" class="headerlink" title="不要使用Exception捕捉所有潜在的异常"></a>不要使用Exception捕捉所有潜在的异常</h3><p>针对具体的异常进行处理，而不是使用Exception捕获所有的异常。这样不利于异常情况的处理，并且如果再次向上抛出时可能会丢书原有的异常信息。 </p>
<h3 id="抛出与抽象相适应的异常"><a href="#抛出与抽象相适应的异常" class="headerlink" title="抛出与抽象相适应的异常"></a>抛出与抽象相适应的异常</h3><p>换句话说，一个方法所抛出的异常应该在一个抽象层次上定义，该抽象层次与该方法做什么相一致，而不一定与方法的底层实现细节相一致。例如，一个从文件、数据库或者 JNDI 装载资源的方法在不能找到资源时，应该抛出某种 ResourceNotFound 异常（通常使用异常链来保存隐含的原因），而不是更底层的 IOException 、 SQLException 或者 NamingException 。</p>
<p>我们有时候在捕获一个异常后抛出另一个封装后的异常信息，并且希望将原始的异常信息也保持起来，<br>throw抛出的是一个新的异常信息，这样势必会导致原有的异常信息丢失，如何保持？<br>在Throwable及其子类中的构造器中都可以接受一个cause参数，该参数保存了原有的异常信息，通过getCause()就可以获取该原始异常信息。</p>
<h3 id="多线程中的异常"><a href="#多线程中的异常" class="headerlink" title="多线程中的异常"></a>多线程中的异常</h3><p>在java多线程程序中，所有线程都不允许抛出未捕获的检测型异常（比如sleep时的InterruptedException),<br>也就是说各个线程需要自己把自己的检测型处理掉。<br>这一点是通过java.lang.Runnable.run()方法声明(因为此方法声明上没有throw exception部分)进行了约束。<br>但是线程依然有可能抛出非检测型异常，当此类异常跑抛出时，线程就会终结，<br>而对于主线程和其他线程完全不受影响，且完全感知不到某个线程抛出的异常(也是说完全无法catch到这个异常)。</p>
<p>如果我们不考虑线程内可能出现的异常而导致线程的终结，那么就有可能造成意想不到的后果。如果是使用线程池的话，就有可能导致线程泄漏，这样的错误可能难以察觉，<br>最终导致程序挂掉或者内存溢出等等意想不到的问题，但是往往不好追踪问题出现的原因。<br><a href="https://www.ibm.com/developerworks/cn/java/j-jtp0924/" target="_blank" rel="external">Java 理论与实践: 嗨，我的线程到哪里去了？</a>这篇文章很好的展示了一个多线程发生异常后产生的一系列后果。</p>
<p>对于线程可以自己处理的异常，比较好解决。我们可以在线程内部捕获异常，作一些处理，防止线程退出。比如，<a href="https://www.ibm.com/developerworks/cn/java/j-jtp0924/" target="_blank" rel="external">Java 理论与实践: 嗨，我的线程到哪里去了？</a>这篇文章中的一个示例：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div></pre></td><td class="code"><pre><div class="line">private class SaferPoolWorker extends Thread &#123;</div><div class="line">    public void run() &#123;</div><div class="line">        IncomingResponse ir;</div><div class="line">        while (true) &#123;</div><div class="line">            ir = (IncomingResponse) queue.getNext();</div><div class="line">            PlugIn plugIn = findPlugIn(ir.getResponseId());</div><div class="line">            if (plugIn != null) &#123;</div><div class="line">        try &#123;</div><div class="line">                    plugIn.handleMessage(ir.getResponse());</div><div class="line">                &#125;</div><div class="line">                catch (RuntimeException e) &#123;</div><div class="line">                    // Take some sort of action; </div><div class="line">                    // - log the exception and move on</div><div class="line">                    // - log the exception and restart the worker thread</div><div class="line">                    // - log the exception and unload the offending plug-in</div><div class="line">                &#125;</div><div class="line">            &#125;</div><div class="line">            else</div><div class="line">                log(&quot;Unknown plug-in for response &quot; + ir.getResponseId());</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>但是，当子线程发生异常时，我们需要父线程或者主线程可以感知子线程的异常，也就是得到子线程产生的异常，然后做一些处理。<a href="http://blog.onlycatch.com/post/Java%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5" target="_blank" rel="external">Java线程池异常处理最佳实践</a>这篇文章给出了很好的总结，<br>摘抄其总结如下：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line">处理线程池中的异常有两种思路： </div><div class="line">1）提交到线程池中的任务自己捕获异常并处理，不抛给线程池 </div><div class="line">2）由线程池统一处理</div><div class="line">对于execute方法提交的线程，有两种处理方式 </div><div class="line">1）自定义线程池并实现afterExecute方法 </div><div class="line">2）给线程池中的每个线程指定一个UncaughtExceptionHandler,由handler来统一处理异常。</div><div class="line">对于submit方法提交的任务，异常处理是通过返回的Future对象进行的。</div></pre></td></tr></table></figure></p>
<h2 id="其他"><a href="#其他" class="headerlink" title="其他"></a>其他</h2><p>还发现了一个比较有趣的异常处理情况，虽然可能很少碰到，但是碰到了可以参考作者的思路。</p>
<p><a href="https://www.ibm.com/developerworks/cn/java/j-ce/" target="_blank" rel="external">技巧：当不能抛出异常时</a>这篇文章介绍了一种不是很常见的情况：即不能处理，也不能抛出异常(包括非检测型异常)时怎么办？</p>
<h2 id="参考"><a href="#参考" class="headerlink" title="参考"></a>参考</h2><p><a href="http://www.ibm.com/developerworks/cn/java/j-lo-exception-misdirection/" target="_blank" rel="external">Java 异常处理的误区和经验总结</a></p>
<p><a href="http://www.importnew.com/18994.html" target="_blank" rel="external">Java异常处理和设计</a></p>
<p><a href="https://www.ibm.com/developerworks/cn/java/j-jtp05254/" target="_blank" rel="external">Java 理论与实践: 关于异常的争论</a></p>

      
    </div>
    <footer class="article-footer">
      <a data-url="http://yukai.space/2016/12/13/java异常的学习/" data-id="cj9nvpdvh002z1ynjlqky8yul" class="article-share-link">分享</a>
      
      
      
  <ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/java/">java</a></li></ul>

    </footer>
  </div>
  
    
 <script src="/jquery/jquery.min.js"></script>
  <div id="random_posts">
    <h2>推荐文章</h2>
    <div class="random_posts_ul">
      <script>
          var random_count =4
          var site = {BASE_URI:'/'};
          function load_random_posts(obj) {
              var arr=site.posts;
              if (!obj) return;
              // var count = $(obj).attr('data-count') || 6;
              for (var i, tmp, n = arr.length; n; i = Math.floor(Math.random() * n), tmp = arr[--n], arr[n] = arr[i], arr[i] = tmp);
              arr = arr.slice(0, random_count);
              var html = '<ul>';
            
              for(var j=0;j<arr.length;j++){
                var item=arr[j];
                html += '<li><strong>' + 
                item.date + ':&nbsp;&nbsp;<a href="' + (site.BASE_URI+item.uri) + '">' + 
                (item.title || item.uri) + '</a></strong>';
                if(item.excerpt){
                  html +='<div class="post-excerpt">'+item.excerpt+'</div>';
                }
                html +='</li>';
                
              }
              $(obj).html(html + '</ul>');
          }
          $('.random_posts_ul').each(function () {
              var c = this;
              if (!site.posts || !site.posts.length){
                  $.getJSON(site.BASE_URI + 'js/posts.js',function(json){site.posts = json;load_random_posts(c)});
              } 
               else{
                load_random_posts(c);
              }
          });
      </script>
    </div>
  </div>

    
<nav id="article-nav">
  
    <a href="/2017/02/07/Vps使用笔记/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">上一篇</strong>
      <div class="article-nav-title">
        
          Vps使用笔记
        
      </div>
    </a>
  
  
    <a href="/2016/12/07/java远程调试学习/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">下一篇</strong>
      <div class="article-nav-title">java远程调试学习</div>
    </a>
  
</nav>

  
</article>
 
     
  <div class="comments" id="comments">
    
     
       
      <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
    
       
      
      
  </div>
 
  

</section>
           
    <aside id="sidebar">
  
    

  
    
    <div class="widget-wrap">
    
      <div class="widget" id="toc-widget-fixed">
      
        <strong class="toc-title">文章目录</strong>
        <div class="toc-widget-list">
              <ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#异常分类"><span class="toc-number">1.</span> <span class="toc-text">异常分类</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#Error："><span class="toc-number">1.1.</span> <span class="toc-text">Error：</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#Exception"><span class="toc-number">1.2.</span> <span class="toc-text">Exception:</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#检测型异常"><span class="toc-number">1.2.1.</span> <span class="toc-text">检测型异常</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#非检测型异常"><span class="toc-number">1.2.2.</span> <span class="toc-text">非检测型异常</span></a></li></ol></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#异常处理"><span class="toc-number">2.</span> <span class="toc-text">异常处理</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#关键字"><span class="toc-number">2.1.</span> <span class="toc-text">关键字</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try-catch-finally执行顺序"><span class="toc-number">2.2.</span> <span class="toc-text">try catch finally执行顺序</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#一些建议"><span class="toc-number">3.</span> <span class="toc-text">一些建议</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#不要使用空的catch块"><span class="toc-number">3.1.</span> <span class="toc-text">不要使用空的catch块</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#在能够处理异常的地方处理异常"><span class="toc-number">3.2.</span> <span class="toc-text">在能够处理异常的地方处理异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#日志打印"><span class="toc-number">3.3.</span> <span class="toc-text">日志打印</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#检测异常与非检测异常的选择"><span class="toc-number">3.4.</span> <span class="toc-text">检测异常与非检测异常的选择</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#不要使用Exception捕捉所有潜在的异常"><span class="toc-number">3.5.</span> <span class="toc-text">不要使用Exception捕捉所有潜在的异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#抛出与抽象相适应的异常"><span class="toc-number">3.6.</span> <span class="toc-text">抛出与抽象相适应的异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#多线程中的异常"><span class="toc-number">3.7.</span> <span class="toc-text">多线程中的异常</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#其他"><span class="toc-number">4.</span> <span class="toc-text">其他</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#参考"><span class="toc-number">5.</span> <span class="toc-text">参考</span></a></li></ol>
          </div>
      </div>
    </div>

  
    

  
    
  
    
  
    

  
    <!--微信公众号二维码-->


  
</aside>

      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-left">
      &copy; 2014 - 2017 于凯&nbsp;|&nbsp;
      主题 <a href="https://github.com/giscafer/hexo-theme-cafe/" target="_blank">Cafe</a>
    </div>
     <div id="footer-right">
      联系方式&nbsp;|&nbsp;debiaoyu@gmail.com
    </div>
  </div>
</footer>
 <script src="/jquery/jquery.min.js"></script>
    </div>
    <nav id="mobile-nav">
  
    <a href="/" class="mobile-nav-link">首页</a>
  
    <a href="/archives" class="mobile-nav-link">归档</a>
  
    <a href="/tools" class="mobile-nav-link">工具</a>
  
    <a href="/page" class="mobile-nav-link">关于</a>
  
</nav>
    <img class="back-to-top-btn" src="/images/fly-to-top.png"/>
<script>
// Elevator script included on the page, already.
window.onload = function() {
  var elevator = new Elevator({
    selector:'.back-to-top-btn',
    element: document.querySelector('.back-to-top-btn'),
    duration: 1000 // milliseconds
  });
}
</script>
      

  
    <script>
      var cloudTieConfig = {
        url: document.location.href, 
        sourceId: "",
        productKey: "e2fb4051c49842688ce669e634bc983f",
        target: "cloud-tie-wrapper"
      };
    </script>
    <script src="https://img1.ws.126.net/f2e/tie/yun/sdk/loader.js"></script>
    

  







<!-- author:forvoid begin -->
<!-- author:forvoid begin -->

<!-- author:forvoid end -->

<!-- author:forvoid end -->



 <script src="/js/is.js"></script>


  <link rel="stylesheet" href="/fancybox/jquery.fancybox.css">
  <script src="/fancybox/jquery.fancybox.pack.js"></script>


<script src="/js/script.js"></script>
<script src="/js/elevator.js"></script>
  </div>
</body>
</html>